### ISSUE TITLE
Adding support of hex codes.

### ISSUE THREAD

**Issue by shitzuu** [OkaeriPoland/okaeri-platform#3]
This would be great if there will be added support of using hex codes in messages.

**Comment by PinkLolicorn** [comment]
This feature should be already supported due to use of `ChatColor.translateAlternateColorcodes` in the codebase. Example of coloring with `#bdeaa0` color code:
```
&x&b&d&e&a&a&0colored string
```

Further improvements are planned to be included in the update, introducing component representation using markdown/html like syntax.
