### ISSUE TITLE
BungeeCord support.

### ISSUE THREAD

**Issue by sadcenter** [OkaeriPoland/okaeri-platform#4]
Are there any plans for the future about adding bungeecord's support, because it would be great :wink:

**Comment by PinkLolicorn** [comment]
Tracking on https://github.com/OkaeriPoland/okaeri-platform/tree/feature/bungee-support

If needed `okaeri-platform-bungee:0.4.0-preview` is available in the repository.

**Comment by PinkLolicorn** [comment]
Version `0.4.0-preview2` is now available featuring setup() method that allows to register own components, also fixes generic Component support.

**Comment by PinkLolicorn** [comment]
Version `0.4.0-preview4` is now available, fixing startup errors, and providing alternative `PlatformScheduler` instead of `BukkitScheduler`.

**Comment by dasavick** [comment]
Commands available from Feb 22 (release `0.4.1`): https://github.com/OkaeriPoland/okaeri-platform/commit/df43804a3e60a93596ef753932f845d3607a1c47
